# Generated by Django 4.2.1 on 2023-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('delivery_date', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_person', models.CharField(max_length=255)),
            ],
        ),
    ]
