# Generated by Django 4.2.3 on 2023-07-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_history',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
