# Generated by Django 4.2.1 on 2023-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.JSONField()),
                ('total_price', models.FloatField()),
            ],
        ),
    ]
