# Generated by Django 4.2.3 on 2023-07-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
        ('delivery', '0002_delivery_customer_name'),
        ('customer', '0002_customer_address_customer_order_history_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='shoppingCart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.shoppingcart'),
        ),
    ]
